### ISSUE TITLE
Some information.

### ISSUE THREAD

**Issue by sabinu** [runxel/GDL-sublime#2]
Can you please elaborate on the GDL Nucleus. Is it comercialy available? Can you try it? Can you make something similar? . . .

sabin.purice@gmail.com

Thank you!

**Comment by runxel** [comment]
Hi Sabinu,
»GDL Nucleus« is a commercial program and was made by Frank Beister (_so it's not by me_).
I have a version here at hand and use it in the daily scripting process. GDL Nucleus acts like a Sublime Text project handler which will use the "build"-functionality of ST and the XML_Converter of ArchiCAD to send the changes to ArchiCAD (and vice versa).
At some points it's still a cumbersome process but it is more comfortable than copying and pasting all the code to ArchiCAD.

/runxel
