### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by borshpro** [runxel/GDL-sublime#3]
Missing keywords:

**Global**
- GLOB_PROJECT_LONGITUDE
- GLOB_PROJECT_LATITUDE

**Geometry**
- sprism_{4}

**Group**
- addgroup{3}

**Comment by runxel** [comment]
~~I can't find any info on "addgroup{3}".~~
found it.
Thanks.
The rest (and many others) are added meanwhile.

**Comment by runxel** [comment]
- GLOB_PROJECT_LONGITUDE
- GLOB_PROJECT_LATITUDE  
  will give a warning and a default value when used in parameterscript anyway...

**Comment by borshpro** [comment]
Dear @runxel, to see all these keywords just follow these steps:
1. Create New project from Default template.
2. Place walls, slabs, roofs, windows and doors in walls, place furniture (objects).
3. Save plan as GDL script.
4. Open script in Sublime and check all non-coloured keywords.
