### ISSUE TITLE
NURBS primitive elements - ARCHICAD 20

### ISSUE THREAD

**Issue by borshpro** [runxel/GDL-sublime#4]
[ Issue details are hidden until final release ]

**Comment by sabinu** [comment]
how do you know this? I can't find any official statement about archicad 20.

**Comment by borshpro** [comment]
I know this as a beta tester of ARCHICAD.

George

**Comment by sabinu** [comment]
can you share more?

**Comment by borshpro** [comment]
Sabinu, NURBS support added to ARCHICAD to achieve smooth connection between ARCHICAD and Rhinoceros + Grasshopper applications.

**Comment by runxel** [comment]
Hi George (@borshpro),
thank you for the contribution.

As you may know, I'm a Beta tester as well.
Two things here:
1) Are you absolutely sure, that this is the final RTM version?
2) Where did you find the full command list?

Besides: I'm wondering if this issue isn't violating our nondisclosure agreement....
This are the reasons why I didn't do anything on this topic already.

Cheers!

**Comment by borshpro** [comment]
Hi Lucas @runxel 
1. I'm pretty sure that GDL syntax will be as currently implemented.
2. It's in the official GDL Reference Guide located in Documentation subfolder (05 GDL Reference Guide.pdf)

Well, I didn't tell anyone about upcoming release except keywords and description that we use in testing also.

**Comment by runxel** [comment]
My documentation folder is nearly empty. There is only some license stuff and the `new features draft` PDF. Might be because I'm currently using the German Beta (?).
Anyway, I will use your list as reference ;)

~~Do you have some info on `addgroup{3}`? (other issue)~~
~~Couldn't find any.~~
Nevermind. Found it.
