### ISSUE TITLE
No longer in Sublime Package Manager

### ISSUE THREAD

**Issue by johnau** [runxel/GDL-sublime#8]
GDL-sublime is no longer available in package control!
Happy to install manually, but package control option was nice.

**Comment by johnau** [comment]
Sorry, was a glitch of some sort.

**Comment by runxel** [comment]
Glad you could figure it out!

There was indeed a problem with PM last year for a short period, due to an error of mine. But this long fixed.  
You can also always double check on the [web page](https://packagecontrol.io/packages/GDL).
